sudo: false

language: node_js

node_js:
#  - "0.12"
  - "iojs"

install:
  - npm install

script:
  - npm run lint
  - npm run cover
  - npm run nsp
  - make install
  - echo $secret_variable
  - echo $non_secret_variable

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
   code_climate:
     repo_token: 67de7a9cad1cc6e224897de8384439e62ce0c8ce70733e02aa2eea964615ab9c

after_success:
  - npm run codeclimate-cover-submit
  - npm run codecov-submit


  
